# Generated by Django 6.0.1 on 2026-07-11 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETLPipeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APISource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=100)),
                ('base_url', models.URLField()),
                ('api_key', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
