# Generated by Django 6.0.1 on 2026-07-11 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETLPipeapp', '0002_apisource'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETLJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('destination_table', models.CharField(max_length=100)),
                ('schedule', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ETLPipeapp.apisource')),
            ],
        ),
    ]
