# Generated by Django 6.0.1 on 2026-07-12 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETLPipeapp', '0003_etljob'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETLHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_date', models.DateTimeField(auto_now_add=True)),
                ('records_processed', models.IntegerField()),
                ('duration', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ETLPipeapp.etljob')),
            ],
        ),
    ]
