# Generated by Django 6.0.1 on 2026-07-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETLPipeapp', '0004_etlhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retry_count', models.IntegerField(default=3)),
                ('batch_size', models.IntegerField(default=1000)),
                ('notification_email', models.EmailField(max_length=254)),
                ('schedule', models.CharField(max_length=50)),
                ('log_level', models.CharField(max_length=20)),
            ],
        ),
    ]
