# Generated by Django 6.0.1 on 2026-08-02 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETLPipeapp', '0005_systemsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apisource',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='etlhistory',
            options={'ordering': ['-execution_date']},
        ),
        migrations.AlterModelOptions(
            name='etljob',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='apisource',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etljob',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apisource',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='etlhistory',
            name='duration',
            field=models.CharField(default='0 Seconds', max_length=50),
        ),
        migrations.AlterField(
            model_name='etlhistory',
            name='records_processed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='etlhistory',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='etljob',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='log_level',
            field=models.CharField(default='INFO', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='schedule',
            field=models.CharField(default='Daily', max_length=50),
        ),
    ]
